version: 2
jobs:

    build_python35:
        working_directory: ~/spot-runner
        docker:
            - image: circleci/python:3.5
        steps: &STEPS
            - checkout
            - run:
                name: Setup venv
                command: |
                    python3 -m venv ~/venv
                    test -f requirements.txt && ~/venv/bin/pip install -r requirements.txt
                    test -f requirements-tests.txt && ~/venv/bin/pip install -r requirements-tests.txt
            - run: ~/venv/bin/pip install -e .
            - run: ~/venv/bin/pytest -vv --tb=native --color=yes tests

    build_python36:
        working_directory: ~/spot-runner
        docker:
            - image: circleci/python:3.6
        steps: *STEPS

workflows:
    version: 2
    build_and_test:
        jobs:
            - build_python35
            - build_python36
